In [1]:
import pandas as pd

Reading Data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0  100.731408         1   10          0           1              1
1  100.154524         0   85          1          -1              0
2  100.507608         1   67          0           0              1
3  100.733942         1   22          0           1              0
4   99.188515         0    9          1           1              0

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1994   98.380707         1   49          0           1              1
1995   98.698819         0   44          1           1              1
1996   99.160195         1   33          1           1              0
1997   99.872501         1   54          0          -1              1
1998  101.245603         0   55          0           0              1

In [5]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          1999 non-null   float64
 1   bodyPain       1999 non-null   int64  
 2   age            1999 non-null   int64  
 3   runnyNose      1999 non-null   int64  
 4   diffBreath     1999 non-null   int64  
 5   infectionProb  1999 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 93.8 KB


In [6]:
df['fever'].value_counts()

99.925767     1
100.991175    1
101.987129    1
99.702520     1
101.247816    1
             ..
100.971644    1
101.304453    1
99.845836     1
101.482958    1
98.489276     1
Name: fever, Length: 1999, dtype: int64

In [7]:
df['diffBreath'].value_counts()

 1    698
-1    663
 0    638
Name: diffBreath, dtype: int64

In [8]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  1999.000000  1999.000000  1999.000000  1999.000000  1999.000000   
mean     99.989574     0.512256    49.957979     0.514757     0.017509   
std       1.143188     0.499975    28.599233     0.499907     0.825151   
min      98.001613     0.000000     1.000000     0.000000    -1.000000   
25%      98.983768     0.000000    26.000000     0.000000    -1.000000   
50%     100.014820     1.000000    49.000000     1.000000     0.000000   
75%     100.980632     1.000000    74.000000     1.000000     1.000000   
max     101.999983     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    1999.000000  
mean        0.506753  
std         0.500079  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

Train Test Splitting 

In [9]:
import numpy as np

In [10]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]
    
    

In [11]:
np.random.permutation(7)

array([0, 1, 6, 3, 4, 5, 2])

In [12]:
train,test=data_split(df,0.2)

In [13]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
966   101.118501         1    2          1          -1              0
240   101.270931         0   47          1           1              1
812    98.760800         1   83          1          -1              0
1824  101.238166         0   68          1           0              0
1244  100.790520         1   71          1           1              1
...          ...       ...  ...        ...         ...            ...
1130   98.354007         1    6          0          -1              0
1294   98.888199         1   69          1          -1              0
860    98.720567         0   29          0           1              1
1459  101.453975         1   97          0          -1              0
1126  101.191210         0   20          0          -1              0

[1600 rows x 6 columns]

In [14]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
256    98.808183         0   51          1           0              0
352    98.994723         1   87          1           0              1
298   101.883465         1   15          1          -1              0
581    98.940383         0   16          1           1              1
1288   98.370154         0   42          0           1              0
...          ...       ...  ...        ...         ...            ...
1616  101.613049         1   68          1          -1              0
650   101.656714         1   37          0          -1              1
1973  101.867487         0   79          0          -1              1
261   101.209140         0   37          0           1              0
1305   99.785675         0    1          0           1              0

[399 rows x 6 columns]

In [15]:
x_train=train[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()
x_test=test[['fever','bodyPain','age','runnyNose','diffBreath']].to_numpy()

In [16]:
y_train=train[['infectionProb']].to_numpy().reshape(1600,)
y_test=test[['infectionProb']].to_numpy().reshape(399,)

In [17]:
y_train

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [18]:
x_train

array([[101.1185012 ,   1.        ,   2.        ,   1.        ,
         -1.        ],
       [101.2709315 ,   0.        ,  47.        ,   1.        ,
          1.        ],
       [ 98.76080016,   1.        ,  83.        ,   1.        ,
         -1.        ],
       ...,
       [ 98.72056698,   0.        ,  29.        ,   0.        ,
          1.        ],
       [101.4539754 ,   1.        ,  97.        ,   0.        ,
         -1.        ],
       [101.1912099 ,   0.        ,  20.        ,   0.        ,
         -1.        ]])

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
clf= LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
inputFeatures=[102,0,12,-1,1]
infProb=clf.predict_proba([inputFeatures])[0][1]

In [26]:
infProb

0.5606581046310164